@base=http://localhost:8000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3Njc4OTUyNzUsInVzZXJfaWQiOjF9.RuYIjVvRIz3ntiHtXh0_tw4cJGk9nMUvrx6GRsk-bIg

####################
#   Users routes   #
####################
POST {{base}}/user HTTP/1.1
Content-Type: application/json

{
    "full_name": "Vitor Souza",
    "email":"vitor.souza@gmail.com",
    "password": "password123"
}

### Login
POST {{base}}/login HTTP/1.1
Content-Type: application/json

{
    "email":"vitor.souza@gmail.com",
    "password": "password123"
}

### Update user
PUT {{base}}/user/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}} 

{
    "full_name": "Vitor Castro",
    "email":"vitor.castro@gmail.com"
}

####################
#   Links routes   #
####################

### ping
GET {{base}}/ping HTTP/1.1
Content-Type: application/json

### get links
GET {{base}}/links HTTP/1.1
Content-Type: application/json

### create link
POST {{base}}/links HTTP/1.1
Content-Type: application/json

###
GET {{base}}/links/{slug} HTTP/1.1
Content-Type: application/json

###
DELETE {{base}}/links/{slug} HTTP/1.1
Content-Type: application/json

###
GET {{base}}/r/{slug} HTTP/1.1
Content-Type: application/json