@base=http://localhost:8000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3NjgwNzAyNDMsInVzZXJfaWQiOjN9.wrH-6fAfBwwu8nlI_N3LiK9jcS4VCvYq_tAoOMseE3g

####################
#   Users routes   #
####################
POST {{base}}/user HTTP/1.1
Content-Type: application/json

{
    "full_name": "Vitor Souza",
    "email":"vitor.souza@gmail.com",
    "password": "password123"
}

### Login
POST {{base}}/login HTTP/1.1
Content-Type: application/json

{
    "email":"vitor.castro@gmail.com",
    "password": "password123"
}

### Update user
PUT {{base}}/user/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}} 

{
    "full_name": "Vitor Castro",
    "email":"vitor.castro@gmail.com"
}

### Delete User
DELETE {{base}}/user/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}} 

####################
#   Links routes   #
####################

### ping
GET {{base}}/ping HTTP/1.1
Content-Type: application/json

### create link
POST {{base}}/links HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}} 

{
    "target_url": "https://svitorz.dev"
}

@slug=https-svitorz-dev
###
GET {{base}}/links/{{slug}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}} 

###
DELETE {{base}}/links/{{slug}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}} 

###
GET {{base}}/r/{{slug}} HTTP/1.1
Content-Type: application/json