@base=http://localhost:8000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3NjgwNzQ2NjAsInVzZXJfaWQiOjR9.3f2yxIsfdjZq7o1U2sx-FyuS_0zButz5wi2WwJCSs_A

####################
#   Users routes   #
####################
POST {{base}}/user HTTP/1.1
Content-Type: application/json

{
    "full_name": "Vitor Souza",
    "email":"vitor.souza@gmail.com",
    "password": "password123"
}

### Login
POST {{base}}/login HTTP/1.1
Content-Type: application/json

{
    "email":"vitor.souza@gmail.com",
    "password": "password123"
}

### Update user
PUT {{base}}/user/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}} 

{
    "full_name": "Vitor Castro",
    "email":"vitor.castro@gmail.com"
}

### Delete User
DELETE {{base}}/user/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}} 

####################
#   Links routes   #
####################

### ping
GET {{base}}/ping HTTP/1.1
Content-Type: application/json

### create link 1
POST {{base}}/links HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}} 

{
    "target_url": "https://svitorz.dev"
}

### create link 2
POST {{base}}/links HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}} 

{
    "target_url": "https://facebook.com"
}

@slug=https-svitorz-dev
@slugTwo=https-facebook-com
###
GET {{base}}/links/{{{{slugTwo}}}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}} 

###
POST {{base}}/links/{{slug}}/deactivate HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}} 

###
GET {{base}}/r/{{slug}} HTTP/1.1
Content-Type: application/json

### Test active slug
GET {{base}}/r/{{{{slugTwo}}}} HTTP/1.1
Content-Type: application/json